"""test running migrations

Revision ID: 11c384dc6e9c
Revises: 3dcb19d4e909
Create Date: 2023-08-03 13:05:19.354848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c384dc6e9c'
down_revision = '3dcb19d4e909'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
