"""test running migrations

Revision ID: 2b17cb740897
Revises: b01a5e1da474
Create Date: 2023-08-03 13:23:36.612359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b17cb740897'
down_revision = 'b01a5e1da474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
