"""test running migrations

Revision ID: 3dcb19d4e909
Revises: 7d701d86bac7
Create Date: 2023-08-03 13:05:04.480606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcb19d4e909'
down_revision = '7d701d86bac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
