"""removed role from user

Revision ID: 4e0a9a886aaa
Revises: e6c1ad387b38
Create Date: 2023-08-14 13:27:03.380658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e0a9a886aaa'
down_revision = 'e6c1ad387b38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('TUTOR', 'STUDENT', name='roleenum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
