"""added category table

Revision ID: 535629132ff6
Revises: ece83322bcd4
Create Date: 2023-08-13 23:19:42.364506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535629132ff6'
down_revision = 'ece83322bcd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_category_association',
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_category_association')
    op.drop_table('category')
    # ### end Alembic commands ###
