"""test running migrations

Revision ID: 66c3a839825f
Revises: abd7aa8ced61
Create Date: 2023-08-03 13:16:02.421241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c3a839825f'
down_revision = 'abd7aa8ced61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
