"""added relation with module in lesson

Revision ID: 676faf540760
Revises: b25d810d06ab
Create Date: 2023-08-14 10:54:04.975174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676faf540760'
down_revision = 'b25d810d06ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('module_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lesson', 'course_module', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.drop_column('lesson', 'module_id')
    # ### end Alembic commands ###
