"""test running migrations

Revision ID: 67bc3565a3ce
Revises: c6e669c962e0
Create Date: 2023-08-03 13:14:01.303865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67bc3565a3ce'
down_revision = 'c6e669c962e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
