"""test running migrations

Revision ID: 85223b60a026
Revises: 2b17cb740897
Create Date: 2023-08-03 14:05:32.224459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85223b60a026'
down_revision = '2b17cb740897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
