"""test running migrations

Revision ID: 9c52d02a6289
Revises: 66c3a839825f
Create Date: 2023-08-03 13:16:37.377163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c52d02a6289'
down_revision = '66c3a839825f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
