"""test running migrations

Revision ID: abd7aa8ced61
Revises: edadf955454d
Create Date: 2023-08-03 13:15:56.745852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd7aa8ced61'
down_revision = 'edadf955454d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
