"""change user_id into id

Revision ID: ad950fe5c1a5
Revises: f8fdd717eff7
Create Date: 2023-07-31 16:38:38.769087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad950fe5c1a5'
down_revision = 'f8fdd717eff7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
