"""removed course lesson relationship

Revision ID: b82e80548c19
Revises: 4e0a9a886aaa
Create Date: 2023-08-16 17:04:56.345034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82e80548c19'
down_revision = '4e0a9a886aaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lesson_course_id_fkey', 'lesson', type_='foreignkey')
    op.drop_column('lesson', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('lesson_course_id_fkey', 'lesson', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###
