"""test running migrations

Revision ID: c6e669c962e0
Revises: 11c384dc6e9c
Create Date: 2023-08-03 13:12:04.611295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e669c962e0'
down_revision = '11c384dc6e9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
