"""set lesson content nullable

Revision ID: dc355b9098f2
Revises: b82e80548c19
Create Date: 2023-08-16 17:15:05.451665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc355b9098f2'
down_revision = 'b82e80548c19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
