"""test running migrations

Revision ID: edadf955454d
Revises: 67bc3565a3ce
Create Date: 2023-08-03 13:15:14.473434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edadf955454d'
down_revision = '67bc3565a3ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
