"""added max length of course title

Revision ID: f9a6e42963e2
Revises: db924bcb0607
Create Date: 2023-08-01 13:40:22.978043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a6e42963e2'
down_revision = 'db924bcb0607'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'is_active')
    # ### end Alembic commands ###
